name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fastqc=0.11.9
  - multiqc=1.12
  - trim-galore=0.6.7
  - hisat2=2.2.1
  - samtools=1.15
  - subread=2.0.1  # for featureCounts
  - parallel=20210922
  - pigz=2.6